MACRO(SUBDIR_INCLUDE_DIRECTORIES curdir)
	FILE(GLOB children RELATIVE ${curdir} ${curdir}/*)
	SET(dirlist "")
	FOREACH(child ${children})
		IF(IS_DIRECTORY ${curdir}/${child} AND EXISTS ${curdir}/${child}/CMakeLists.txt AND EXISTS ${curdir}/${child}/include)
			# message( "APPENDING: " ${curdir}/${child}/include )
			LIST(APPEND dirlist ${curdir}/${child}/include)
		ENDIF()
	ENDFOREACH()
	include_directories( ${dirlist} )
ENDMACRO()
