name: linux

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  BUILD_TYPE: Release

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: gather apt packets
      run: sudo apt update && sudo apt install gcc-10 g++-10 libboost-all-dev python3 python3-pip doxygen
      shell: bash

    - name: gather python packets
      run: pip3 install jinja2 Pygments --user
      shell: bash

    - name: configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      env:
        CC:   gcc-10
        CXX:  g++-10

    - name: build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: test
      working-directory: ${{github.workspace}}/build
      run: ctest --output-on-failure --output-junit ${{github.workspace}}/build/report.xml

    - name: generate docs
      working-directory: ${{github.workspace}}/build
      run: make docs

    - uses: actions/upload-artifact@v2
      with:
        name: documentation
        path: ${{github.workspace}}/build/docs
        retention-days: 5

  generate-latex-paper:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2

      - name: gather apt packets
        run: |
          sudo apt update && sudo apt-get install
            texlive-latex-base \
            texlive-fonts-recommended \
            texlive-fonts-extra \
            texlive-latex-extra \
            texlive-latex-extra-doc \
            texlive-lang-polish \
            biber
        shell: bash

      - name: generate paper
        run: |
          cd ${{github.workspace}}/paperwork/paper
          pdflatex -synctex=1 -interaction=nonstopmode --shell-escape master_degree || true
          biber master_degree
          pdflatex -synctex=1 -interaction=nonstopmode --shell-escape master_degree || true

      - uses: actions/upload-artifact@v2
        with:
          name: master degree paper
          path: ${{github.workspace}}/paperwork/paper/master_degree.pdf
          retention-days: 30
